version: "3.8"

services:
  app:
    build: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=abc
      - POSTGRES_USER=abc
      - POSTGRES_DB=abc
